# Generated by Django 4.0.7 on 2022-08-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_adress',
            new_name='shop_address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shopname',
            new_name='shop_name',
        ),
    ]
