# Generated by Django 4.0.7 on 2022-08-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_adress_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='opder_date',
            new_name='order_date',
        ),
    ]
